### ISSUE TITLE
pdfMake.vfs

### ISSUE THREAD

**Issue by sourabh-ambarshetti** [kaburkett/ngx-pdfmake-example#1]
Facing Problem in  pdfMake.vfs = pdfFonts.pdfMake.vfs;
Cannot assign to 'vfs' because it is a read-only property.

**Comment by kaburkett** [comment]
I updated the readme on how to run the example. I've installed and ran this repo just now to make sure it still builds and runs.

This repo is an example of how to use the pdfmake library with angular only. If your issue is outside of running this example, I encourage you to look for issues in the pdfmake library that may resemble your problem.

**Comment by kaburkett** [comment]
For example, others report your issue here:

https://github.com/bpampuch/pdfmake/issues/1769

with solution suggestions here:

https://stackoverflow.com/a/56535907/6119323

**Comment by kaburkett** [comment]
I see. I implemented the change suggested in that incident I linked to. Pull and see if it builds for you now.

https://github.com/kaburkett/ngx-pdfmake-example/commit/e77b8e74a973cf24c3af050dca54533728db4713
